#####################################################################################
from typing import Iterable, Optional

from sciml.core.sampler import SamplerBase
from sciml.core.loss import LossBase
from sciml.core.model import ModelBase
from sciml.core.evaluation import Evaluation
from sciml.utils import checker

#####################################################################################
class Objective():
    """
    Parameters necessary to define an objective function or part of it.

    An ``Objective`` combines a sampler with one or more loss functions,
    defining a single optimization objective. During evaluation, a new
    class:`Context` is generated by the sampler, the model is evaluated,
    and the requested loss functions are computed.

    Multiple objectives can be used simultaneously during training. This
    allows different sampling strategies (e.g. interior points, boundary
    conditions and experimental data) to be evaluated independently while
    sharing the same model.
    """
    def __init__(
            self,
            sampler: SamplerBase,
            losses: Iterable[LossBase],
        ) -> None:
        """
        Parameters
        ----------
        sampler : SamplerBase
            Sampler used to generate training data.
        losses : Iterable[LossBase]
            Loss functions to be evaluated during training.
        """
        # ---------------------------------------------------------------------------
        self.sampler = sampler
        self.losses = losses
        # ---------------------------------------------------------------------------
        return

    def evaluate(
            self,
            model: ModelBase,
            names: Optional[Iterable[str]],
        ) -> Optional[Evaluation]:
        """
        Evaluate the objective.

        A new context is generated by the sampler and passed to the model.
        The model stores its outputs in the context, after which the
        selected loss functions are evaluated.

        Parameters
        ----------
        model : ModelBase
            Model to be evaluated.
        names : Iterable[str] or None
            Names of the loss functions to evaluate. If ``None``, all
            losses associated with the objective are evaluated.

        Returns
        -------
        Evaluation or None
            Evaluation containing the computed losses, weights and metadata.
            Returns ``None`` if none of the requested losses belong to this
            objective.
        """
        # ---------------------------------------------------------------------------
        # > Validation
        checker.is_dtype(model, ModelBase)

        # ---------------------------------------------------------------------------
        # > Check whether at least one requested loss belongs to this objective
        if names is None:
            check = True
        else:
            check = not set(names).isdisjoint((loss.name for loss in self.losses))

        # ---------------------------------------------------------------------------
        # > Evaluate objective
        if check:
            context = self.sampler.next()
            model.compute(context)
            
            evaluation = Evaluation(values={}, weights={}, metadata={})
            for loss in self.losses:
                if (names is None) or (loss.name in names):
                    evaluation.values[loss.name] = loss.evaluate(context)
                    evaluation.weights[loss.name] = loss.weight
            
            return evaluation

        # ---------------------------------------------------------------------------
        # > Skip evaluation
        return None

#####################################################################################
