#####################################################################################
from typing import Iterable, Optional

from sciml.core.sampler import SamplerBase
from sciml.core.loss import LossBase
from sciml.core.model import ModelBase
from sciml.core.evaluation import Evaluation
from sciml.utils import checker

#####################################################################################
class Validation():
    """
    Parameters necessary to define an objective function or part of it.

    An ``Objective`` combines a sampler with one or more loss functions,
    defining a single optimization objective. During evaluation, a new
    class:`Context` is generated by the sampler, the model is evaluated,
    and the requested loss functions are computed.

    Multiple objectives can be used simultaneously during training. This
    allows different sampling strategies (e.g. interior points, boundary
    conditions and experimental data) to be evaluated independently while
    sharing the same model.
    """

    def __init__(
            self,
            name: str,
            frequency: int,
            sampler: SamplerBase,
            losses: Iterable[LossBase]
        ) -> None:
        """
        Parameters
        ----------
        name : str
            Unique identifier for the validation.
        frequency : int
            Frequency of validation (e.g., every n iterations).
        sampler : SamplerBase
            Sampler used to generate validation data.
        losses : Iterable[LossBase]
            Loss functions to be evaluated during validation.
        """
        # ---------------------------------------------------------------------------
        self.name = name
        self.frequency = frequency
        self.sampler = sampler
        self.losses = losses
        # ---------------------------------------------------------------------------
        return

    def evaluate(
            self,
            iteration: int,
            model: ModelBase,
        ) -> Optional[Evaluation]:
        """
        Evaluate the objective.

        A new context is generated by the sampler and passed to the model.
        The model stores its outputs in the context, after which the
        selected loss functions are evaluated.

        Parameters
        ----------
        model : ModelBase
            Model to be evaluated.

        Returns
        -------
        Evaluation or None
            Evaluation containing the computed losses and metadata or None
            based on interation and frequency.
        """
        # ---------------------------------------------------------------------------
        # > Validation
        checker.is_integer(iteration)
        checker.is_dtype(model, ModelBase)

        # ---------------------------------------------------------------------------
        # > Evaluate objective
        evaluation = Evaluation(values={}, weights={}, metadata={})
        evaluation.metadata["name"] = self.name

        if (iteration % self.frequency == 0) or (iteration == 1):

            context = self.sampler.next()
            model.compute(context)

            for loss in self.losses:
                evaluation.values[loss.name] = loss.evaluate(context).item()
            
            return evaluation

        else:
            
            for loss in self.losses:
                evaluation.values[loss.name] = None
            
            return evaluation

#####################################################################################
